### PR TITLE
update json

### PR DESCRIPTION
**Pull request by JaskRendix**
PR updates runtime + json

### CODE REVIEW

**Comment by JaskRendix** [comment]
@Murmele this is the update of the actual version, if they merge the other PR, then I'm going to add an additional PR

**Comment by Murmele** [comment]
Something is not working yet here

**Comment by JaskRendix** [comment]
@Murmele you're right, the PR has been merged on Tuxemon, so I updated the file again with the last version, let's see what happens.

**Comment by JaskRendix** [comment]
@Murmele it was the wrong package, can we put two different packages?

with this was success x86-64
```
                {
                    "type": "file",
                    "url": "https://files.pythonhosted.org/packages/90/28/3c6843e6b203999be2660d3f114be196f2182dcac533dc764ad320c9184d/pydantic_core-2.14.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
                    "sha256": "036137b5ad0cb0004c75b579445a1efccd072387a36c7f217bb8efd1afbe5245"
                },
```
how can I add this one?
```
https://files.pythonhosted.org/packages/8f/2d/919d3642da44bc9d9c60a2e7bbda04633fc3ffbd6768c355ac0d7e2424d7/pydantic_core-2.14.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
5aa90562bc079c6c290f0512b21768967f9968e4cfea84ea4ff5af5d917016e4
```

**Comment by JaskRendix** [comment]
@Murmele success, I needed to use a different package for pydantic-core (one for x86_64 and another for aarch64)

**Comment by Murmele** [comment]
Thanks!

**Pull request merged**
